# Generated by Django 6.0.5 on 2026-07-06 10:27

import apps.accounts.managers
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('role', models.CharField(choices=[('STUDENT', 'دانشجو'), ('TEACHER', 'مدرس'), ('ADMIN', 'مدیر')], default='STUDENT', max_length=10, verbose_name='نقش')),
                ('instrument', models.CharField(blank=True, max_length=50, verbose_name='ساز اصلی')),
                ('skill_level', models.CharField(blank=True, choices=[('BEGINNER', 'مقدماتی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته')], max_length=12, verbose_name='سطح هنری')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.accounts.managers.CustomUserManager()),
            ],
        ),
    ]
