# Generated by Django 6.0.5 on 2026-07-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentprofile',
            name='instrument',
            field=models.CharField(blank=True, choices=[('PIANO', 'پیانو'), ('GUITAR', 'گیتار'), ('VIOLIN', 'ویولن'), ('TAR', 'تار'), ('SETAR', 'سه\u200cتار'), ('SANTUR', 'سنتور'), ('FLUTE', 'فلوت'), ('NEY', 'نی'), ('UD', 'عود'), ('KAMANCHEH', 'کمانچه'), ('DAF', 'دف'), ('TOMBAK', 'تمبک'), ('VOCAL', 'آواز')], max_length=20, null=True, verbose_name='ساز'),
        ),
    ]
