# Generated by Django 6.0.5 on 2026-07-06 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('authority', models.CharField(blank=True, max_length=100, verbose_name='Authority')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='RefID')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('student_name', models.CharField(blank=True, max_length=150, verbose_name='نام دانشجو')),
                ('student_phone', models.CharField(blank=True, max_length=11, verbose_name='موبایل دانشجو')),
                ('student_national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی دانشجو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='school.course', verbose_name='دوره')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
