# Generated by Django 6.0.5 on 2026-07-07 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='شرح حال')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='تخصص')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سال\u200cهای تجربه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'مدرسین',
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='نامک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='شهریه (تومان)')),
                ('duration_weeks', models.PositiveIntegerField(default=12, verbose_name='مدت دوره (هفته)')),
                ('level', models.CharField(choices=[('BEGINNER', 'مقدماتی'), ('ELEMENTARY', 'ابتدایی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته'), ('PROFESSIONAL', 'حرفه\u200cای')], default='BEGINNER', max_length=15, verbose_name='سطح')),
                ('instrument', models.CharField(choices=[('PIANO', 'پیانو'), ('GUITAR', 'گیتار'), ('VIOLIN', 'ویولن'), ('TAR', 'تار'), ('SETAR', 'سه\u200cتار'), ('SANTUR', 'سنتور'), ('FLUTE', 'فلوت'), ('NEY', 'نی'), ('UD', 'عود'), ('KAMANCHEH', 'کمانچه'), ('DAF', 'دف'), ('TOMBAK', 'تمبک'), ('VOCAL', 'آواز')], max_length=20, verbose_name='ساز')),
                ('image', models.URLField(blank=True, verbose_name='تصویر دوره')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='school.teacher', verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='پاییز ۱۴۰۳', max_length=100, verbose_name='ترم')),
                ('schedule', models.JSONField(blank=True, default=dict, verbose_name='برنامه هفتگی')),
                ('capacity', models.PositiveIntegerField(default=12, verbose_name='ظرفیت')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('ENDED', 'پایان\u200cیافته'), ('CANCELED', 'لغو\u200cشده')], default='ACTIVE', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.course', verbose_name='دوره')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='school.teacher', verbose_name='مدرس کلاس')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=100, verbose_name='ترم')),
                ('status', models.CharField(choices=[('ENROLLED', 'ثبت\u200cنام\u200cشده'), ('DROPPED', 'انصرافی'), ('COMPLETED', 'تکمیل\u200cشده')], default='ENROLLED', max_length=10, verbose_name='وضعیت ثبت\u200cنام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.class', verbose_name='کلاس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'class_ref')},
            },
        ),
    ]
